spring.application.name=gestion-gimnasios

spring.datasource.url=jdbc:postgresql://localhost:5432/gimnasio_tfg
spring.datasource.username=postgres
spring.datasource.password=user
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.jakarta.persistence.schema-generation.database.action=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.show-sql=true


spring.jpa.hibernate.ddl-auto=create-drop
